<a href="https://colab.research.google.com/github/vedpd/Udacity-Deep-Learning-Nanodegree/blob/main/Udacity_DL_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np

In [42]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

In [43]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [44]:
x.shape

(2, 3, 1)

In [45]:
y=  np.array([[1,2,3],[4,5,6]])

In [46]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
y.shape

(2, 3)

In [48]:
z= np.array([1,2,3])

In [49]:
z

array([1, 2, 3])

In [50]:
z.shape

(3,)

In [51]:
m=  np.array([[1,2,3],])

In [52]:
m

array([[1, 2, 3]])

In [53]:
m.shape

(1, 3)

## Operations on matrices using numpy
### element wise addition and multiplication

In [54]:
# using list from python

values = [1,2,3,4,5]

for i in range(len(values)):
  values[i]+=5

print (values)

[6, 7, 8, 9, 10]


In [55]:
# using numpy
value = np.array([1,2,3,4,5])

value = value + 5

print (value)

[ 6  7  8  9 10]


In [56]:
values = np.array(values) + 5
print(values)
# Alternate way

type(values)

values = values + 5
print (values)

[11 12 13 14 15]
[16 17 18 19 20]


In [57]:
# Let's do some multiplication

some_array =  np.ndarray([1,2,1,2])

x= np. multiply(some_array, 2)

y = some_array * 2 # if some_array is already converted to numpy ndarray format

print ( x )

print ( y )

[[[[2.e-323 2.e-323]]

  [[2.e-323 0.e+000]]]]
[[[[2.e-323 2.e-323]]

  [[2.e-323 0.e+000]]]]


In [58]:
# get the square of a matrix

a = np.array([[1,3],[5,7]])

In [59]:
a

array([[1, 3],
       [5, 7]])

In [60]:
# element wise multiplication
square = a*a

In [61]:
square

array([[ 1,  9],
       [25, 49]])

In [62]:
sq_new = np.multiply(a,a)

In [63]:
sq_new

array([[ 1,  9],
       [25, 49]])

In [64]:
b = np.array([[2,4],[6,8]])

In [65]:
a + b

array([[ 3,  7],
       [11, 15]])

## Numpy Matrix multiplication

In [66]:
# Type 1 : Element wise

m = np.array([[1,2,3],[4,5,6]])

In [67]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
n= m * 0.25

print(n)

[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]


In [69]:
m *  n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [70]:
np.multiply (m,n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [71]:
# Type 2 : Matmul - behaves like dot product in 2 dimensions

a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
a.shape

(2, 4)

In [73]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
b.shape

(4, 3)

In [75]:
c = np.matmul(a,b)
print(c)
c.shape


[[ 70  80  90]
 [158 184 210]]


(2, 3)

In [76]:
# Using dot product for the same matrix multiplication
d = np.dot(a,b)

In [77]:
print(d)

d.shape

[[ 70  80  90]
 [158 184 210]]


(2, 3)

In [78]:
# Checking for wrong size of multiplication
# size of a = (2,4)
# size of b = (4,3)
# output of dot product of a and b = (2,3) size matrix
# let's try doing the reverse

In [79]:
print(np.matmul(b,a))

ValueError: ignored

In [ ]:
print(np.dot(b,a))

While these functions return the same results for two dimensional data, you should be careful about which you choose when working with other data shapes. You can read more about the differences, and find links to other NumPy functions, in the [matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul) and [dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) documentation.

## Matrix Transpose

In [80]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [82]:
m_T = m.T

m_T[3][1] = 200

m_T

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [83]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

Since m.T and m share same memory and m.T is a different way to index.

Hence, it is important to stay careful while updating values of matrix

In [84]:
# Neural networ use case

inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [85]:
inputs.shape

(1, 4)

In [86]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [87]:
weights.shape

(3, 4)

In [89]:
np.matmul(inputs,weights)

ValueError: ignored

In [91]:
np.matmul(inputs,weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [92]:
np.matmul(weights,inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

Thus same matrix multiplication is showed here for both cases but just into a transposed form